### ISSUE TITLE
Minor Differences in RMSE Results for LS_beta, PBCT_beta, and PBCT

### ISSUE THREAD

**Issue by JIM3766** [ppguo/PBCT#1]
Hi, first of all, I want to say that this is an outstanding piece of work. I really appreciate the effort and thought put into developing this project.

![image](https://github.com/user-attachments/assets/8295c114-2297-4f00-8250-ac0be5e0e351)
I encountered a question while running `PBCT_offline_unlabeled.py` and `PBCT_offline.py` from your code. As shown in the attached screenshot, the output results reveal only a minor difference between the `LS_beta_RMSE`, `PBCT_beta_RMSE`, and `PBCT_RMSE` values. Could you please advise if this outcome is reasonable?

Thank you again for your assistance.

**Comment by ppguo** [comment]
Hello! This is a really good question, and I think the phenomenon you’ve observed is reasonable.

1. The accuracy of a single run is often influenced by random fluctuations in dataset splitting, so it’s possible for the phenomenon you mentioned to appear in individual experiments.
2. Accuracy is not the only criterion we use to evaluate model quality. We chose the complete-view model as the final prediction model mainly because it considers all features, without the prior feature selection that the partial-view model performs. Therefore, we believe the parameters selected by the complete-view model are more meaningful as a reference.

I hope this answer is helpful to you.

**Comment by JIM3766** [comment]
Thank you for the clarification. This is very helpful. I appreciate your assistance!
